
mode:         local   # if "remote", bind to 0.0.0.0
serverPort:   4567    # ports <1024 require running with sudo
envoyAddress: localhost
envoyPort:    9001

assetRoot: "dist"   # root for html, js, css files
storeRoot: "."      # root for ceStore.yaml and contract libraries

store: "ceStore.yaml"

masterAccount: "3030303030303030303030303030303030303030"   # base16
