
mode:         local   # if "remote", bind to 0.0.0.0
serverPort:   3000    # ports <1024 require running with sudo
envoyAddress: ec2-3-16-70-198.us-east-2.compute.amazonaws.com
envoyPort:    9001

assetRoot: "dist"   # root for html, js, css files
storeRoot: "."      # root for ceStore.yaml and contract libraries

store: "ceStore.yaml"

masterAccount: "3030303030303030303030303030303030303030"   # base16
