
mode: local    # if "remote", listen on "serverPort" and bind to 0.0.0.0; else listen on default sinatra port of 4567
serverPort: 80

projectRoot: "."

store: "ceStore.yaml"

masterAccount: "3030303030303030303030303030303030303030"   # base16
